checks:
    javascript: true
build:
    environment:
        variables:
            JWT_SECRET: 'scrutnizeryes'
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
